name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Publish .NET Core Project
      run: dotnet publish Pixels/Pixels.csproj -c Release -o release --nologo
    - name: Change base-tag in index.html from / to Pixels
      run: sed -i 's/<base href="\/" \/>/<base href="\/Pixels\/" \/>/g' release/wwwroot/index.html
    
    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll
    
    - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: release/wwwroot
        
